version: '3.8'

services:

  dvd-rental-api:
    build:
      context: .
      dockerfile: ./dockerfiles/node.dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './:/app:rw'
      - '/app/node_modules/'
    depends_on:
      - dvd-rental-db
      - dvd-rental-cache

  dvd-rental-db:
    build:
      context: .
      dockerfile: ./dockerfiles/db.dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvdrental
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

  dvd-rental-cache:
    image: 'redis:7-alpine'
    ports:
      - "6379:6379"


  # Utility containers
  # For example: docker-compose run --rm api-npm i -D @types/express
  api-npm:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - './:/app:rw'
  api-npx:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npx']
    volumes:
      - './:/app:rw'


volumes:
  db-volume:
    driver: local